### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by by-cx** [abohmeed/cronmanager#4]
Hi,

I made some changes to your project. I fixed the situations when the command is executed too quickly for Prometheus to notice, fixed run dimension to be set correctly from beginning and added last dimension that can be used to check if the cronjob actually run or not in time. I cannot create PR because it's missing licence so I dunno if it's legal or not to change the code. Can you please add a licence to your repo?

**Comment by abohmeed** [comment]
Hello
I've added a GPL license. 
Thanks for pointing that out.

**Comment by by-cx** [comment]
Hi, thanks. I have finally added the PR.
